name: CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Using Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.17.1
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run build checks
        run: npm run build:check

      - name: Run build packages
        run: npm run build:packages
