name: PR Branch Policy

on:
  pull_request:

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure PR into main is only from develop or hotfix/*
        if: github.base_ref == 'main'
        run: |
          case "${{ github.head_ref }}" in
            develop|hotfix/*) ;;
            *)
              echo "❌ Pull Requests to 'main' are only allowed from 'develop', or 'hotfix/*' branches."
              exit 1
              ;;
          esac

      - name: Ensure PR into develop is only from main, feature/* or fix/*
        if: github.base_ref == 'develop'
        run: |
          case "${{ github.head_ref }}" in
            main|feature/*|fix/*) ;;
            *)
              echo "❌ Pull Requests to 'develop' are only allowed from 'main', 'feature/*', or 'fix/*' branches."
              exit 1
              ;;
          esac
